http:
  routers:
    backend-api:
      rule: "Host(`mail.sudoinnovation.tech`) && (Path(`/health`) || PathPrefix(`/api`))"
      entryPoints:
        - websecure
      service: backend-api-svc
      priority: 100
      tls: {}

    frontend-web:
      rule: "Host(`mail.sudoinnovation.tech`)"
      entryPoints:
        - websecure
      service: frontend-web-svc
      priority: 1
      tls: {}

  services:
    backend-api-svc:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    frontend-web-svc:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
