http:
  routers:
    backend-api:
      rule: "Host(`mail.sudoinnovation.tech`) && (PathPrefix(`/health`) || PathPrefix(`/api`))"
      entryPoints:
        - websecure
      service: backend-api-svc
      priority: 100
      tls: {}

    frontend-web:
      rule: "Host(`mail.sudoinnovation.tech`)"
      entryPoints:
        - websecure
      service: frontend-web-svc
      priority: 1
      tls: {}

  serversTransports:
    backend-timeout:
      forwardingTimeouts:
        dialTimeout: 10s
        responseHeaderTimeout: 120s
        idleConnTimeout: 120s

  services:
    backend-api-svc:
      serversTransport: backend-timeout
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    frontend-web-svc:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
